"""Add auto increment id

Revision ID: 52d0db93f8b7
Revises: 54456124a52f
Create Date: 2021-03-10 22:40:42.015991-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52d0db93f8b7'
down_revision = '54456124a52f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_ride_tags',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ride_id'], ['ride.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'ride_id', 'tag_id')
    )
    op.drop_table('user_ride_tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_ride_tag',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ride_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ride_id'], ['ride.id'], name='user_ride_tag_ride_id_fkey'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name='user_ride_tag_tag_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_ride_tag_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'ride_id', 'tag_id', name='user_ride_tag_pkey')
    )
    op.drop_table('user_ride_tags')
    # ### end Alembic commands ###
