"""Remove unique constraint from RTA

Revision ID: 54456124a52f
Revises: 6894c5975cd5
Create Date: 2021-03-10 21:17:33.425530-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54456124a52f'
down_revision = '6894c5975cd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
