"""Change input time from epoch to datetime again

Revision ID: 82d93d741ad3
Revises: 8adca074e2a8
Create Date: 2021-03-03 16:08:30.920188-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82d93d741ad3'
down_revision = '8adca074e2a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride', sa.Column('original_air_time', sa.DateTime(), nullable=True))
    op.add_column('ride', sa.Column('scheduled_start_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ride', 'original_air_time')
    op.drop_column('ride', 'scheduled_start_time')
    # ### end Alembic commands ###
