"""Change input time from epoch to datetime

Revision ID: 8adca074e2a8
Revises: b0e71fe64ffc
Create Date: 2021-03-03 15:59:08.867463-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8adca074e2a8'
down_revision = 'b0e71fe64ffc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
