"""Add avatar and bio to UserProfile table

Revision ID: a13c3a9360bb
Revises: 26c3f1e5d1ca
Create Date: 2021-03-24 18:23:26.353201-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a13c3a9360bb'
down_revision = '26c3f1e5d1ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('avatar', sa.String(), nullable=True))
    op.add_column('user_profile', sa.Column('bio', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'bio')
    op.drop_column('user_profile', 'avatar')
    # ### end Alembic commands ###
