"""Fix to created_at

Revision ID: b0e71fe64ffc
Revises: 9626dc91cb40
Create Date: 2021-03-02 22:41:15.509810-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0e71fe64ffc'
down_revision = '9626dc91cb40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
